import { useMemo, useState } from 'react';
import { ArrowRight, CalendarDays, Clock3, Eye, Film, History as HistoryIcon, Play, RefreshCw, Sparkles, UserRound } from 'lucide-react';
import { Link } from 'wouter';
import { getListSessionsQueryKey, useListSessions } from '@workspace/api-client-react';
import { PodiumShell, PageError, PageLoading } from '@/components/PodiumShell';
import { formatSeconds, getLocalRecordings, getSessionKey } from '@/lib/session';

export default function History() {
  const [local] = useState(getLocalRecordings);
  const query = useListSessions({ sessionKey: getSessionKey() }, { query: { queryKey: getListSessionsQueryKey({ sessionKey: getSessionKey() }) } });
  const sessions = useMemo(() => [...(query.data ?? []), ...local.filter((item) => !(query.data ?? []).some((server) => server.id === item.id))], [query.data, local]);
  if (query.isLoading) return <PodiumShell><PageLoading label="Gathering your takes" /></PodiumShell>;
  if (query.isError) return <PodiumShell><PageError onRetry={() => query.refetch()} /></PodiumShell>;
  const chartSessions = sessions.filter((session) => session.fillersPerMinute !== null).slice(0, 8).reverse();
  const chartMax = Math.max(...chartSessions.map((session) => session.fillersPerMinute ?? 0), 1);
  return <PodiumShell><div className="mx-auto max-w-6xl px-5 py-8 lg:px-12 lg:py-12"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="font-mono text-[10px] uppercase tracking-[.2em] text-accent">Your sessions</p><h1 className="mt-4 font-serif text-5xl tracking-[-.05em] sm:text-6xl">The archive.</h1><p className="mt-4 max-w-lg text-muted-foreground">Every rehearsal is evidence. Browse the work, notice the pattern, come back stronger.</p></div><button onClick={() => query.refetch()} className="flex items-center gap-2 self-start rounded-full border border-border px-4 py-2.5 text-sm hover:border-accent hover:text-accent" data-testid="button-refresh-history"><RefreshCw size={15} /> Refresh</button></div>
    {chartSessions.length > 0 && <section className="mt-12 rounded-[1.5rem] bg-primary p-6 text-primary-foreground sm:p-8" data-testid="section-filler-trend"><div className="flex items-start justify-between gap-5"><div><p className="font-mono text-[10px] uppercase tracking-[.18em] text-[hsl(var(--sidebar-primary))]">Your signal</p><h2 className="mt-2 font-serif text-3xl">Filler words over time.</h2><p className="mt-2 text-sm text-primary-foreground/60">A lower bar is not the goal every time. It is simply one pattern worth noticing.</p></div><Sparkles size={20} className="text-[hsl(var(--sidebar-primary))]" /></div><div className="mt-8 flex h-40 items-end gap-2 border-b border-primary-foreground/15 pb-0 sm:gap-4">{chartSessions.map((session) => <div key={session.id} className="group flex h-full flex-1 flex-col justify-end gap-2"><div className="text-center font-mono text-[10px] text-primary-foreground/65 opacity-0 transition group-hover:opacity-100">{session.fillersPerMinute}/m</div><div className="min-h-1 rounded-t-md bg-[hsl(var(--sidebar-primary))] transition-all" style={{ height: `${Math.max(4, ((session.fillersPerMinute ?? 0) / chartMax) * 100)}%` }} /><span className="truncate text-center font-mono text-[9px] text-primary-foreground/45">{formatShortDate(session.createdAt)}</span></div>)}</div><div className="mt-5 flex items-center gap-2 text-xs text-primary-foreground/55"><ActivityDot /> Most recent: {chartSessions.at(-1)?.fillersPerMinute}/min</div></section>}
    <div className="mt-12">{sessions.length === 0 ? <EmptyHistory /> : <div className="overflow-hidden rounded-[1.5rem] border border-border bg-card">{sessions.map((session, index) => <article key={`${session.id}-${index}`} className="grid gap-4 border-b border-border p-5 last:border-0 sm:grid-cols-[1fr_auto] sm:items-center sm:p-7"><div><div className="flex flex-wrap items-center gap-2"><span className="rounded-full bg-accent/12 px-2.5 py-1 font-mono text-[10px] uppercase tracking-[.12em] text-accent">{session.categoryName}</span><span className="flex items-center gap-1 font-mono text-[10px] text-muted-foreground"><CalendarDays size={12} /> {formatDate(session.createdAt)}</span>{session.feedbackSummary && <span className="flex items-center gap-1 rounded-full bg-[hsl(151_35%_48%/.1)] px-2 py-1 font-mono text-[10px] text-[hsl(151_35%_35%)]"><Sparkles size={11} /> reviewed</span>}</div><h2 className="mt-4 font-serif text-2xl">{session.topicTitle}</h2><div className="mt-3 flex flex-wrap gap-4 text-xs text-muted-foreground"><span className="flex items-center gap-1.5"><Clock3 size={14} /> Research {formatSeconds(session.researchSeconds)}</span><span className="flex items-center gap-1.5"><HistoryIcon size={14} /> Speaking {formatSeconds(session.speakingSeconds)}</span>{session.fillersPerMinute !== null && <span className="flex items-center gap-1.5"><ActivityDot /> {session.fillersPerMinute}/min fillers</span>}{session.eyeContactPercent !== null && <span className="flex items-center gap-1.5"><Eye size={14} /> {session.eyeContactPercent}% eye contact</span>}{session.postureScore !== null && <span className="flex items-center gap-1.5"><UserRound size={14} /> {session.postureScore} posture</span>}</div></div><div className="flex items-center gap-2 sm:flex-col sm:items-end">{session.recordingUrl ? <a href={session.recordingUrl} target="_blank" rel="noreferrer" className="flex items-center gap-2 rounded-full bg-primary px-4 py-2.5 text-xs font-semibold text-primary-foreground" data-testid={`link-play-recording-${session.id}`}><Play size={13} fill="currentColor" /> Play recording</a> : <span className="flex items-center gap-2 rounded-full bg-secondary px-4 py-2.5 text-xs text-muted-foreground"><Film size={14} /> Metadata only</span>}</div></article>)}</div>}</div><div className="mt-8 flex items-center justify-between rounded-2xl border border-border bg-secondary/45 p-5"><p className="text-sm text-muted-foreground">Ready for another round?</p><Link href="/" className="flex items-center gap-2 text-sm font-semibold hover:text-accent" data-testid="link-new-session">Start a new session <ArrowRight size={15} /></Link></div></div></PodiumShell>;
}
function formatDate(value: string) { const date = new Date(value); return Number.isNaN(date.getTime()) ? 'Recent' : new Intl.DateTimeFormat('en', { month: 'short', day: 'numeric', year: 'numeric' }).format(date); }
function formatShortDate(value: string) { const date = new Date(value); return Number.isNaN(date.getTime()) ? '—' : new Intl.DateTimeFormat('en', { month: 'numeric', day: 'numeric' }).format(date); }
function ActivityDot() { return <span className="inline-block h-2 w-2 rounded-full bg-accent" />; }
function EmptyHistory() { return <div className="rounded-[1.5rem] border border-dashed border-border bg-card p-12 text-center sm:p-20"><div className="mx-auto grid h-14 w-14 place-items-center rounded-full bg-secondary text-accent"><HistoryIcon size={23} /></div><h2 className="mt-6 font-serif text-3xl">Your archive starts here.</h2><p className="mx-auto mt-3 max-w-sm text-sm leading-6 text-muted-foreground">Your saved takes will live here. Start with one question and see where it takes you.</p><Link href="/" className="mt-7 inline-flex items-center gap-2 rounded-full bg-primary px-5 py-3 text-sm font-semibold text-primary-foreground" data-testid="link-empty-start">Enter the practice room <ArrowRight size={15} /></Link></div>; }